AWSTemplateFormatVersion: "2010-09-09"

Description: S3 CloudFormation Template

Resources:
  RintuS3BucketCFN:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256